apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-service
  name: hello-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-service
  type: ClusterIP
status:
  loadBalancer: {}
