apiVersion: v1
kind: Service
metadata:
  labels:
    app: japp-server
  name: japp-server
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: japp-server
  type: ClusterIP
status:
  loadBalancer: {}
