apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: auth-server
  type: ClusterIP
status:
  loadBalancer: {}
